name: RepairIt
description: It is an plugin that repairs items used or all inventory by players for a price.
main: me.AhmHkn.RepairIt.Main
version: 2.1
author: AhmHkn
depend:
  - Vault
commands:
  repair:
    description: Plugin's command.
  repairit:repair:
    description: Plugin's command.
  tamir:
    description: Pluginin genel komutudur.
  repairit:tamir:
    description: Pluginin genel komutudur.
